# Global plugins
[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'fuenor/qfixhowm'

[[plugins]]
repo = 'osyo-manga/unite-qfixhowm'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'chrisbra/vim-diff-enhanced'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo ='scrooloose/nerdtree'

[[plugins]]
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'bkad/CamelCaseMotion'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'natebosch/vim-lsc'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'liuchengxu/vista.vim'

# Lazy plugins

## Insert mode

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

## Python
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

## Go
[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go','gohtmltmpl']

## HTML
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft =  ['html', 'htmlcheetah', 'gohtmltmpl', 'javascript', 'markdown', 'typescript']

[[plugins]]
repo = 'othree/html5.vim'
on_ft =  ['html', 'htmlcheetah','gohtmltmpl']

[[plugins]]
repo = 'chrisgillis/vim-bootstrap3-snippets'
on_ft =  ['html', 'htmlcheetah', 'gohtmltmpl']

# Javascript

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript']

[[plugins]]
repo = 'benjie/neomake-local-eslint.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'flowtype/vim-flow'
on_ft = ['javascript']
hook_post_update = '''
  let cmd = 'npm install -g flow-bin'
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
hook_post_update = '''
  let cmd = 'npm install -g typescript'
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'ianks/vim-tsx'
on_ft = ['typescript']

[[plugins]]
repo = 'fleischie/vim-styled-components'
on_ft = ['javascript', 'javascript.jsx', 'typescript']

[[plugins]]
repo = 'sbdchd/neoformat'
on_ft = ['javascript', 'javascript.jsx', 'json', 'typescript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

# CSS

[[plugins]]
repo = 'hail2u/vim-css3-syntax.git'
on_ft = ['css', 'scss', 'javascript', 'javascript.jsx']

# Markdown
[[plugins]]
repo = 'previm/previm'
rev = 'add-plantuml-plugin'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

## PowerShell
[[plugins]]
repo = 'miiton/vim-ps1'
on_ft = ['ps1']

## Config
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml','tml']

[[plugins]]
repo = 'mrk21/yaml-vim'
on_ft = ['yaml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

## PHP
[[plugins]]
repo = 'nelsyeung/twig.vim'
on_ft = ['twig']

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']

## Nginx
[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ['nginx']

## GraphQL
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

## Julia
# [[plugins]]
# repo = 'JuliaEditorSupport/julia-vim'
# on_ft = ['julia']

## Ruby
[[plugins]]
repo = 'uplus/deoplete-solargraph'
on_ft = ['ruby']

## Terraform
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf', 'terraform']
