[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'fuenor/qfixhowm'

[[plugins]]
repo = 'osyo-manga/unite-qfixhowm'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'chrisbra/vim-diff-enhanced'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go','gohtmltmpl']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft =  ['html','htmlcheetah','gohtmltmpl']

[[plugins]]
repo = 'othree/html5.vim'
on_ft =  ['html', 'htmlcheetah','gohtmltmpl']

[[plugins]]
repo = 'chrisgillis/vim-bootstrap3-snippets'
on_ft =  ['html', 'htmlcheetah', 'gohtmltmpl']

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'miiton/vim-ps1'
on_ft = ['ps1']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml','tml']

[[plugins]]
repo = 'mrk21/yaml-vim'
on_ft = ['yaml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'pmsorhaindo/syntastic-local-eslint.vim'
on_ft = ['javascript']
