# Global plugins
[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'fuenor/qfixhowm'

[[plugins]]
repo = 'osyo-manga/unite-qfixhowm'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'chrisbra/vim-diff-enhanced'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Lazy plugins
## Insert mode
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1


## Python
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

## Go
[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go','gohtmltmpl']

## HTML
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft =  ['html','htmlcheetah','gohtmltmpl', 'javascript','markdown']

[[plugins]]
repo = 'othree/html5.vim'
on_ft =  ['html', 'htmlcheetah','gohtmltmpl']

[[plugins]]
repo = 'chrisgillis/vim-bootstrap3-snippets'
on_ft =  ['html', 'htmlcheetah', 'gohtmltmpl']

# Javascript

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript']

[[plugins]]
repo = 'mtscout6/syntastic-local-eslint.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

# Markdown
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

## PowerShell
[[plugins]]
repo = 'miiton/vim-ps1'
on_ft = ['ps1']

## Config
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml','tml']

[[plugins]]
repo = 'mrk21/yaml-vim'
on_ft = ['yaml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
